apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secu2-sa
rules:
- apiGroups: [""]
  resources:
     - "nodes"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
     - "pods"
     - "pods/log"
  verbs: ["get", "list", "create", "delete", "watch"]
